name 'example42-stunnel'
version '2.0.10'

author 'Victor Garcia'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/victorgp/puppet-stunnel'
summary 'Puppet module for stunnel'
description 'This module installs and manages stunnel. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
